-- MySQL Script generated by MySQL Workbench
-- Wed Mar 27 17:35:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Alquiler-vivienda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Alquiler-vivienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Alquiler-vivienda` DEFAULT CHARACTER SET utf8 ;
USE `Alquiler-vivienda` ;

-- -----------------------------------------------------
-- Table `Alquiler-vivienda`.`PROPIETARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-vivienda`.`PROPIETARIO` (
  `id_propietario` INT NOT NULL,
  `telefono` INT NULL,
  `Escritura` VARCHAR(45) NULL,
  PRIMARY KEY (`id_propietario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquiler-vivienda`.`NOMBRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-vivienda`.`NOMBRE` (
  `primer_nombre` INT NOT NULL,
  `segundo_nombre` VARCHAR(45) NOT NULL,
  `apellido_paterno` VARCHAR(45) NOT NULL,
  `apellido_materno` VARCHAR(45) NOT NULL,
  `INQUILINO_id_inquilino` INT NOT NULL,
  PRIMARY KEY (`INQUILINO_id_inquilino`),
  CONSTRAINT `fk_NOMBRE_INQUILINO1`
    FOREIGN KEY (`INQUILINO_id_inquilino`)
    REFERENCES `Alquiler-vivienda`.`INQUILINO` (`id_inquilino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquiler-vivienda`.`INQUILINO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-vivienda`.`INQUILINO` (
  `id_inquilino` INT NOT NULL,
  `edad` INT NOT NULL,
  `comprobante_ingresos` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id_inquilino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquiler-vivienda`.`ALQUILER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-vivienda`.`ALQUILER` (
  `id_alquiler` INT NOT NULL,
  `num_pago` INT NOT NULL,
  `inicio_contrato` DATE NOT NULL,
  `INQUILINO_id_inquilino` INT NOT NULL,
  PRIMARY KEY (`id_alquiler`, `INQUILINO_id_inquilino`),
  INDEX `fk_ALQUILER_INQUILINO1_idx` (`INQUILINO_id_inquilino` ASC) VISIBLE,
  CONSTRAINT `fk_ALQUILER_INQUILINO1`
    FOREIGN KEY (`INQUILINO_id_inquilino`)
    REFERENCES `Alquiler-vivienda`.`INQUILINO` (`id_inquilino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquiler-vivienda`.`VIVIENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-vivienda`.`VIVIENDA` (
  `id_vivienda` INT NOT NULL,
  `PROPIETARIO_id_propietario` INT NOT NULL,
  `ALQUILER_id_alquiler` INT NOT NULL,
  PRIMARY KEY (`id_vivienda`, `PROPIETARIO_id_propietario`, `ALQUILER_id_alquiler`),
  INDEX `fk_VIVIENDA_PROPIETARIO1_idx` (`PROPIETARIO_id_propietario` ASC) VISIBLE,
  INDEX `fk_VIVIENDA_ALQUILER1_idx` (`ALQUILER_id_alquiler` ASC) VISIBLE,
  CONSTRAINT `fk_VIVIENDA_PROPIETARIO1`
    FOREIGN KEY (`PROPIETARIO_id_propietario`)
    REFERENCES `Alquiler-vivienda`.`PROPIETARIO` (`id_propietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VIVIENDA_ALQUILER1`
    FOREIGN KEY (`ALQUILER_id_alquiler`)
    REFERENCES `Alquiler-vivienda`.`ALQUILER` (`id_alquiler`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquiler-vivienda`.`DESCRIPCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-vivienda`.`DESCRIPCION` (
  `construccion` VARCHAR(45) NULL,
  `cuartos` VARCHAR(45) NULL,
  `baños` VARCHAR(45) NULL,
  `pisos` VARCHAR(45) NULL,
  `VIVIENDA_id_vivienda` INT NOT NULL,
  PRIMARY KEY (`VIVIENDA_id_vivienda`),
  CONSTRAINT `fk_DESCRIPCION_VIVIENDA1`
    FOREIGN KEY (`VIVIENDA_id_vivienda`)
    REFERENCES `Alquiler-vivienda`.`VIVIENDA` (`id_vivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquiler-vivienda`.`DIRECCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-vivienda`.`DIRECCION` (
  `calle` VARCHAR(45) NOT NULL,
  `num_ext` INT NOT NULL,
  `num_int` INT NOT NULL,
  `colonia` VARCHAR(45) NULL,
  `cp` INT NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `entidad_federativa` VARCHAR(45) NOT NULL,
  `VIVIENDA_id_vivienda` INT NOT NULL,
  PRIMARY KEY (`VIVIENDA_id_vivienda`),
  CONSTRAINT `fk_DIRECCION_VIVIENDA1`
    FOREIGN KEY (`VIVIENDA_id_vivienda`)
    REFERENCES `Alquiler-vivienda`.`VIVIENDA` (`id_vivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquiler-vivienda`.`SERVICIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-vivienda`.`SERVICIOS` (
  `servicio1` VARCHAR(45) NOT NULL,
  `servicio2` VARCHAR(45) NOT NULL,
  `servicio3` VARCHAR(45) NOT NULL,
  `VIVIENDA_id_vivienda` INT NOT NULL,
  PRIMARY KEY (`VIVIENDA_id_vivienda`),
  CONSTRAINT `fk_SERVICIOS_VIVIENDA1`
    FOREIGN KEY (`VIVIENDA_id_vivienda`)
    REFERENCES `Alquiler-vivienda`.`VIVIENDA` (`id_vivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquiler-vivienda`.`COMPROBANTE_PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-vivienda`.`COMPROBANTE_PAGO` (
  `folio` INT NOT NULL,
  `monto` DECIMAL(20) NULL,
  `ALQUILER_id_alquiler` INT NOT NULL,
  PRIMARY KEY (`folio`, `ALQUILER_id_alquiler`),
  INDEX `fk_COMPROBANTE_PAGO_ALQUILER1_idx` (`ALQUILER_id_alquiler` ASC) VISIBLE,
  CONSTRAINT `fk_COMPROBANTE_PAGO_ALQUILER1`
    FOREIGN KEY (`ALQUILER_id_alquiler`)
    REFERENCES `Alquiler-vivienda`.`ALQUILER` (`id_alquiler`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquiler-vivienda`.`NOMBRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-vivienda`.`NOMBRE` (
  `primer_nombre` INT NOT NULL,
  `segundo_nombre` VARCHAR(45) NOT NULL,
  `apellido_paterno` VARCHAR(45) NOT NULL,
  `apellido_materno` VARCHAR(45) NOT NULL,
  `INQUILINO_id_inquilino` INT NOT NULL,
  PRIMARY KEY (`INQUILINO_id_inquilino`),
  CONSTRAINT `fk_NOMBRE_INQUILINO1`
    FOREIGN KEY (`INQUILINO_id_inquilino`)
    REFERENCES `Alquiler-vivienda`.`INQUILINO` (`id_inquilino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
